### ISSUE TITLE
Add message for `$/accountVP` when not connected

### ISSUE THREAD

**Issue by mobiusTripper-crypto** [mobiusTripper-crypto/beetswars-v2#92]
in the card where `$/accountVP` is shown. when the user is not connected. show ?? or somehow prompt them to connect.

Also while adding that ... a popover, or text somewhere explaining why a person would connect their wallet ... and that isn't only a connect no wallet information is save or some other disclaimer <- (or no disclaimer?)

**Comment by RnZ3** [comment]
the whole account VP line will show if three conditions are true:
- pages shows latest round
- vote state active
- account connected
otherwise it'll just disappear.

Agree an explanation why to connect at all and that it is safe to do so would be useful - maybe a popover icon next to the connect button

**Comment by RnZ3** [comment]
... or maybe we could have an 'about' page thats explains the thing in its whole ...
